/*globals define, _*/

/**
 * Generated by DecoratorGenerator
 */

define([
    'js/Decorators/DecoratorBase',
    './DiagramDesigner/SimpleModelDecorator.DiagramDesignerWidget',
    './PartBrowser/SimpleModelDecorator.PartBrowserWidget'
], function (DecoratorBase, SimpleModelDecoratorDiagramDesignerWidget, SimpleModelDecoratorPartBrowserWidget) {

    'use strict';

    var DECORATOR_ID = 'SimpleModelDecorator';

    function SimpleModelDecorator(params) {
        var opts = _.extend({loggerName: this.DECORATORID}, params);

        DecoratorBase.apply(this, [opts]);

        this.logger.debug('SimpleModelDecorator ctor');
    }

    _.extend(SimpleModelDecorator.prototype, DecoratorBase.prototype);
    SimpleModelDecorator.prototype.DECORATORID = DECORATOR_ID;

    /*********************** OVERRIDE DecoratorBase MEMBERS **************************/

    SimpleModelDecorator.prototype.initializeSupportedWidgetMap = function () {
        this.supportedWidgetMap = {
            DiagramDesigner: SimpleModelDecoratorDiagramDesignerWidget,
            PartBrowser: SimpleModelDecoratorPartBrowserWidget
        };
    };

    return SimpleModelDecorator;
});
