/*globals define*/
/*jshint node:true, browser:true*/

/**
 * Generated by PluginGenerator 0.14.0 from webgme on Wed Dec 02 2015 15:06:02 GMT-0600 (CST).
 */

define([
    'plugin/PluginConfig',
    'plugin/PluginBase',
    'common/util/ejs',
    'C2Core/xmljsonconverter',
    'C2Core/ModelTraverserMixin',
    'DeploymentExporter/Templates/Templates',
    'FederatesExporter/RTIVisitors',
    'FederatesExporter/PubSubVisitors',
], function (
    PluginConfig,
    PluginBase,
    ejs,
    JSON2XMLConverter,
    ModelTraverserMixin,
    TEMPLATES,
    RTIVisitors,
    PubSubVisitors
    ) {
    'use strict';

    /**
     * Initializes a new instance of DeploymentExporter.
     * @class
     * @augments {PluginBase}
     * @classdesc This class represents the plugin DeploymentExporter.
     * @constructor
     */
    var DeploymentExporter = function () {
        // Call base class' constructor.
        PluginBase.call(this);
        ModelTraverserMixin.call(this);
        PubSubVisitors.call(this);
        RTIVisitors.call(this);

        this._jsonToXml = new JSON2XMLConverter.Json2xml();
    };

    // Prototypal inheritance from PluginBase.
    DeploymentExporter.prototype = Object.create(PluginBase.prototype);
    DeploymentExporter.prototype.constructor = DeploymentExporter;

    /**
     * Gets the name of the DeploymentExporter.
     * @returns {string} The name of the plugin.
     * @public
     */
    DeploymentExporter.prototype.getName = function () {
        return 'DeploymentExporter';
    };

    /**
     * Gets the semantic version (semver.org) of the DeploymentExporter.
     * @returns {string} The version of the plugin.
     * @public
     */
    DeploymentExporter.prototype.getVersion = function () {
        return '0.1.0';
    };

    /**
     * Gets the configuration structure for the DeploymentExporter.
     * The ConfigurationStructure defines the configuration for the plugin
     * and will be used to populate the GUI when invoking the plugin from webGME.
     * @returns {object} The version of the plugin.
     * @public
     */
    DeploymentExporter.prototype.getConfigStructure = function () {
        var baseURLDefault = 'https://editor.webgme.org',
            usernameDefault = 'guest',
            allFederateTypes = '';

        if(window){
            baseURLDefault = window.location.protocol + window.location.pathname + window.location.pathname + window.location.host;
        }

        if(WebGMEGlobal && WebGMEGlobal.Client){
            usernameDefault =WebGMEGlobal.userInfo._id;
        }

        if(this.federateTypes){
            for(var typeKey in this.federateTypes){
                allFederateTypes+=typeKey + ' '
            }
            allFederateTypes.trim();
        }

        return [
            {
                name: 'exportVersion',
                displayName: 'version',
                description: 'The version of the model to be exported',
                value: '0.0.1',
                valueType: 'string',
                readOnly: false
            },{
                name: 'isRelease',
                displayName: 'release',
                description: 'Is the model a release version?   ',
                value: false,
                valueType: 'boolean',
                readOnly: false
            },{
                name: 'groupId',
                displayName: 'Maven GroupID',
                description: 'The group ID to be included in the Maven POMs',
                value: 'org.webgme.' + usernameDefault,
                valueType: 'string',
                readOnly: false
            },{
                name: 'c2wVersion',
                displayName: 'C2W version',
                description: 'The version of the C2W foundation to be used',
                value: '0.0.1-SNAPSHOT',
                valueType: 'string',
                readOnly: false
            },{
                name: 'repositoryUrlSnapshot',
                displayName: 'Repository URL for snapshots',
                description: 'The URL of the repository where the packaged components should be deployed.',
                value: 'http://c2w-cdi.isis.vanderbilt.edu:8088/repository/snapshots/',
                valueType: 'string',
                readOnly: false
            },{
                name: 'repositoryUrlRelease',
                displayName: 'Repository URL for releases',
                description: 'The URL of the repository where the packaged components should be deployed.',
                value: 'http://c2w-cdi.isis.vanderbilt.edu:8088/repository/internal/',
                valueType: 'string',
                readOnly: false       
            }
        ];
    };

    /**
     * Main function for the plugin to execute. This will perform the execution.
     * Notes:
     * - Always log with the provided logger.[error,warning,info,debug].
     * - Do NOT put any user interaction logic UI, etc. inside this method.
     * - callback always has to be called even if error happened.
     *
     * @param {function(string, plugin.PluginResult)} callback - the result callback
     */
    DeploymentExporter.prototype.main = function (callback) {
        // Use self to access core, project, result, logger etc from PluginBase.
        // These are all instantiated at this point.
        var self = this,
            generateFiles,
            numberOfFilesToGenerate,
            finishExport,
            pomModel = {};

        self.fileGenerators = [];
        self.fom_sheets = {};
        self.federates = [];
        self.interactions = {};
        self.interactionRoots = [];
        self.objects      = {};
        self.objectRoots = [];
        self.attributes   = {};

        self.projectName = self.core.getAttribute(self.rootNode, 'name');

        pomModel.projectName = self.projectName;
        pomModel.groupId = self.getCurrentConfig().groupId.trim();
        pomModel.projectVersion = "0.0.1" + (self.getCurrentConfig().isRelease ? "" : "-SNAPSHOT");
        pomModel.c2wVersion = self.getCurrentConfig().c2wVersion;
        pomModel.repositoryUrlSnapshot = self.getCurrentConfig().repositoryUrlSnapshot;
        pomModel.repositoryUrlRelease = self.getCurrentConfig().repositoryUrlRelease;
        pomModel.federates = self.federates;

        //Add POM generator
        self.fileGenerators.push(function(artifact, callback){
            artifact.addFile('pom.xml', ejs.render(TEMPLATES['execution_pom.xml.ejs'], pomModel), function (err) {
                if (err) {
                    callback(err);
                    return;
                }else{
                    callback();
                }
            });
        });

        self.fomModel = {
            federationname: self.projectName,
            objects: [],
            interactions: []
        };

        //Add FED generator
        self.fileGenerators.push(function(artifact, callback){
            
            var interactionTraverser = function(interaction){
                var intModel = {
                    interaction:interaction,
                    parameters:interaction.parameters,
                    children:[]
                };
                interaction.children.forEach(function(child){
                    intModel.children.push(interactionTraverser(child));
                });
                return ejs.render(TEMPLATES["fedfile_siminteraction.ejs"], intModel);
            }

            self.fomModel.interactions = [];
            self.interactionRoots[0].children.forEach(function(inta){
                self.fomModel.interactions.push(interactionTraverser(inta));
            });
            

            var objectTraverser = function(object){
                var objModel = {
                    name:object.name,
                    attributes:object.attributes,
                    children:[]
                };
                object.children.forEach(function(child){
                    objModel.children.push(objectTraverser(child));
                });
                return ejs.render(TEMPLATES["fedfile_simobject.ejs"], objModel);
            }

            self.fomModel.objects = []
            self.objectRoots[0].children.forEach(function(obj){
                self.fomModel.objects.push(objectTraverser(obj));
            });

            artifact.addFile('src/fom/' + self.projectName + '.fed', ejs.render(TEMPLATES['fedfile.fed.ejs'], self.fomModel), function (err) {
                if (err) {
                    callback(err);
                    return;
                }else{
                    callback();
                }
            });
        });
    
        self.scriptModel = {
            'script': {
                'expect': []
            }
        };
            
        //Add basic script xml for testing
        self.fileGenerators.push(function(artifact, callback){
            self.federates.forEach(function (fed){
                self.scriptModel.script.expect.push({'@federateType':fed.name});
            });

            artifact.addFile('src/experiments/' + 'default' + '/' + 'script.xml', self._jsonToXml.convertToString( self.scriptModel ) , function (err) {
                if (err) {
                    callback(err);
                    return;
                }else{
                    callback();
                }
            });
        });

        generateFiles = function(artifact, doneBack){
            if(numberOfFilesToGenerate > 0){ 
                self.fileGenerators[self.fileGenerators.length - numberOfFilesToGenerate](artifact, function(err){
                    if (err) {
                        callback(err, self.result);
                        return;
                    }
                    numberOfFilesToGenerate--;
                    if(numberOfFilesToGenerate > 0){

                        generateFiles(artifact, doneBack);
                    }else{
                        doneBack();
                     }
                });                
            }else{
                doneBack();
            }
        }

        finishExport = function(err){

            //var outFileName = self.projectName + '.json'
            var artifact = self.blobClient.createArtifact(self.projectName.trim().replace(/\s+/g,'_') +'_Deployment_Files');

            numberOfFilesToGenerate = self.fileGenerators.length;
            if(numberOfFilesToGenerate > 0){
                generateFiles(artifact, function(err){
                    if (err) {
                        callback(err, self.result);
                        return;
                    }

                    self.blobClient.saveAllArtifacts(function (err, hashes) {
                        if (err) {
                            callback(err, self.result);
                            return;
                        }

                        // This will add a download hyperlink in the result-dialog.
                        for (var idx = 0; idx < hashes.length; idx++) {
                            self.result.addArtifact(hashes[idx]);

                            var artifactMsg = 'Deployment package ' + self.blobClient.artifacts[idx].name + ' was generated with id:[' + hashes[idx] + ']';
                            var buildURL = "'http://c2w-cdi.isis.vanderbilt.edu:8080/job/c2w-pull/buildWithParameters?GME_ARTIFACT_ID="+hashes[idx]+"'"
                            artifactMsg += '<br><a title="Build package..." '+
                                    'onclick="window.open(' + buildURL + ', \'Build System\'); return false;">Build artifact..</a>';
                            self.createMessage(null, artifactMsg );

                        };

                        
                        // This will save the changes. If you don't want to save;
                        // exclude self.save and call callback directly from this scope.
                        self.save('DeploymentExporter updated model.', function (err) {
                            if (err) {
                                callback(err, self.result);
                                return;
                            }
                            self.result.setSuccess(true);
                            callback(null, self.result);
                        });
                    });
                })

            }else{
                self.result.setSuccess(true);
                callback(null, self.result);
            }
            
        }

        self.visitAllChildrenFromRootContainer(self.rootNode, function(err){
            if(err)
                self.logger.error(err);
            else
                finishExport(err);
        });

    };

    DeploymentExporter.prototype.visit_Federate = function(node, parent, context){
        var self = this,
            ret = {context:context},
            nodeType = self.core.getAttribute( self.getMetaType( node ), 'name' ),
            fed = {name:self.core.getAttribute(node, 'name')},
            nodeAttrNames;
        self.logger.info('Visiting a Federate');

        nodeAttrNames = self.core.getAttributeNames(node);
        for ( var i = 0; i < nodeAttrNames.length; i += 1 ) {
            fed[nodeAttrNames[i]] = self.core.getAttribute( node, nodeAttrNames[i]);
        }   

        self.federates.push(fed);

        if(nodeType != 'Federate'){
            try{
                ret = self['visit_' + nodeType](node, parent, context);
            }catch(err){
                self.logger.debug('No visitor function for ' + nodeType);
            }
        }

        return ret;
    };

    DeploymentExporter.prototype.getVisitorFuncName = function(nodeType){
        var self = this,
            visitorName = 'generalVisitor';
        if(nodeType){
            visitorName = 'visit_'+ nodeType;
            if(nodeType.endsWith('Federate')){
                visitorName = 'visit_' + 'Federate';
            }
            
        }
        //self.logger.debug('Genarated visitor Name: ' + visitorName);
        return visitorName;   
    }

    DeploymentExporter.prototype.getPostVisitorFuncName = function(nodeType){
        var self = this,
            visitorName = 'generalPostVisitor';
        if(nodeType){
            visitorName = 'post_visit_'+ nodeType;
            if(nodeType.endsWith('Federate')){
                visitorName = 'post_visit_' + 'Federate';
            }
        }
        //self.logger.debug('Genarated post-visitor Name: ' + visitorName);
        return visitorName;
        
    }

    DeploymentExporter.prototype.getChildSorterFunc = function(nodeType, self){
        var self = this,
            visitorName = 'generalChildSorter';

        var generalChildSorter = function(a, b) {

            //a is less than b by some ordering criterion : return -1;
            //if(self.isMetaTypeOf(a, self.META['Types'])){
            //    return -1;
            //}
            //a is greater than b by the ordering criterion: return 1;
            //if(self.isMetaTypeOf(b, self.META['Types'])){
            //    return 1;
            //}

            // a equal to b:
            return 0;
        };
        return generalChildSorter;
        
    }

    DeploymentExporter.prototype.excludeFromVisit = function(node){
        var self = this,
            exclude = false;

        exclude = exclude || self.isMetaTypeOf(node, self.META['Language [CASIM]']) || self.isMetaTypeOf(node, self.META['Language [C2WT]']);
        return exclude; 

    }

        /*
    * Rest of TRAVERSAL CODE:
    * - PubSubVisitors.js
    * - RTIVisitors.js
    * - C2Federates folder for Federate specific vistors
    */

    DeploymentExporter.prototype.ROOT_visitor = function(node){
        var self = this;
        self.logger.info('Visiting the ROOT');

        var root = {
            "@id": 'model:' + '/root',
            "@type": "gme:root",
            "model:name": self.projectName,
            "gme:children": []
        };

        return {context:{parent: root}};
    }
    

    DeploymentExporter.prototype.calculateParentPath = function(path){
        if(!path){
            return null;
        }
        var pathElements = path.split('/');
        pathElements.pop();
        return pathElements.join('/');
    }

    return DeploymentExporter;
});