/*globals define*/
/*jshint node:true, browser:true*/

/**
 * Generated by PluginGenerator 0.14.0 from webgme on Wed Dec 02 2015 15:05:52 GMT-0600 (CST).
 */

define([
    'plugin/PluginConfig',
    'plugin/PluginBase',
    'C2Core/ModelTraverserMixin',
    'C2Core/xmljsonconverter',
    'C2Federates/GenericFederate',
    'C2Federates/CPNFederate'
], function (
    PluginConfig,
    PluginBase,
    ModelTraverserMixin,
    JSON2XMLConverter,
    GenericFederate,
    CPNFederate
    ) {
    'use strict';

    /**
     * Initializes a new instance of FederatesExporter.
     * @class
     * @augments {PluginBase}typ
     * @classdesc This class represents the plugin FederatesExporter.
     * @constructor
     */
    var FederatesExporter = function () {
        // Call base class' constructor.

        this.federateTypes = this.federateTypes || {};  

        PluginBase.call(this);
        ModelTraverserMixin.call(this);
        GenericFederate.call(this);
        CPNFederate.call(this);
        this._jsonToXml = new JSON2XMLConverter.Json2xml();
    };

    // Prototypal inheritance from PluginBase.
    FederatesExporter.prototype = Object.create(PluginBase.prototype);
    FederatesExporter.prototype.constructor = FederatesExporter;

    /**
     * Gets the name of the FederatesExporter.
     * @returns {string} The name of the plugin.
     * @public
     */
    FederatesExporter.prototype.getName = function () {
        return 'FederatesExporter';
    };

    /**
     * Gets the semantic version (semver.org) of the FederatesExporter.
     * @returns {string} The version of the plugin.
     * @public
     */
    FederatesExporter.prototype.getVersion = function () {
        return '0.1.0';
    };

    /**
     * Gets the configuration structure for the FederatesExporter.
     * The ConfigurationStructure defines the configuration for the plugin
     * and will be used to populate the GUI when invoking the plugin from webGME.
     * @returns {object} The version of the plugin.
     * @public
     */
    FederatesExporter.prototype.getConfigStructure = function () {
        var baseURLDefault = 'https://editor.webgme.org',
            usernameDefault = 'guest',
            allFederateTypes = '';

        if(window){
            baseURLDefault = window.location.protocol + window.location.pathname + window.location.pathname + window.location.host;
        }

        if(WebGMEGlobal && WebGMEGlobal.Client){
            usernameDefault = WebGMEGlobal.Client.getUserId();
        }

        if(this.federateTypes){
            for(var typeKey in this.federateTypes){
                allFederateTypes+=typeKey + ' '
            }
            allFederateTypes.trim();
        }

        return [
            {
                name: 'includedFederateTypes',
                displayName: 'include',
                description: 'The Types of federates included in this export',
                value: allFederateTypes,
                valueType: 'string',
                readOnly: false
            },{
                name: 'urlBase',
                displayName: 'URL Base',
                description: 'The base address of webGME where the model is accessible',
                value: baseURLDefault,
                valueType: 'string',
                readOnly: false
            },{
                name: 'useGit',
                displayName: 'Check into Git',
                description: 'Check into GIT version control instead of download',
                value: false,
                valueType: 'boolean',
                readOnly: false
            },{
                name: 'gitURL',
                displayName: 'Repository URL',
                description: 'The address of GIT Repository where the artifacts are deposited',
                value: baseURLDefault,
                valueType: 'string',
                readOnly: false
            },{
                name: 'gitUser',
                displayName: 'GIT Username',
                description: 'The username for GIT Repository where the artifacts are deposited',
                value: usernameDefault,
                valueType: 'string',
                readOnly: false
            },{
                name: 'gitPass',
                displayName: 'GIT Password',
                description: 'The password for GIT Repository where the artifacts are deposited.<br> WARNING: The password may be submitted through a non ecncripted channel.',
                value: '',
                valueType: 'string',
                readOnly: false
            },
        ];
    };

    /**
     * Main function for the plugin to execute. This will perform the execution.
     * Notes:
     * - Always log with the provided logger.[error,warning,info,debug].
     * - Do NOT put any user interaction logic UI, etc. inside this method.
     * - callback always has to be called even if error happened.
     *
     * @param {function(string, plugin.PluginResult)} callback - the result callback
     */
    FederatesExporter.prototype.main = function (callback) {
        // Use self to access core, project, result, logger etc from PluginBase.
        // These are all instantiated at this point.
        var self = this,
            numberOfFilesToGenerate,
            finishExport,
            generateFiles;

        self.fom_sheets = {};
        self.interactions = {};
        self.objects      = {};
        self.attributes   = {};
        self.federates = {};

        self.getCurrentConfig().includedFederateTypes.trim().split(" ").forEach(function(e){
            if(self.federateTypes.hasOwnProperty(e)){
                self.federateTypes[e].includeInExport = true;
            }
        });

        // Using the logger.
        //self.logger.debug('This is a debug message.');
        //self.logger.info('This is an info message.');
        //self.logger.warn('This is a warning message.');
        //self.logger.error('This is an error message.');

        // Using the coreAPI to make changes.

        self.fileGerenrators = [];

        generateFiles = function(artifact, doneBack){
            if(numberOfFilesToGenerate > 0){ 
                self.fileGerenrators[self.fileGerenrators.length - numberOfFilesToGenerate](artifact, function(err){
                    if (err) {
                        callback(err, self.result);
                        return;
                    }
                    numberOfFilesToGenerate--;
                    if(numberOfFilesToGenerate > 0){

                        generateFiles(artifact, doneBack);
                    }else{
                        doneBack();
                     }
                });                
            }else{
                doneBack();
            }
        }

        finishExport = function(err){

            //var outFileName = self.projectName + '.json'
            var artifact = self.blobClient.createArtifact('generatedFiles');

            numberOfFilesToGenerate = self.fileGerenrators.length;
            if(numberOfFilesToGenerate > 0){
                generateFiles(artifact, function(err){
                    if (err) {
                        callback(err, self.result);
                        return;
                    }

                    self.blobClient.saveAllArtifacts(function (err, hashes) {
                        if (err) {
                            callback(err, self.result);
                            return;
                        }
                        // This will add a download hyperlink in the result-dialog.
                        self.result.addArtifact(hashes[0]);
                        
                        // This will save the changes. If you don't want to save;
                        // exclude self.save and call callback directly from this scope.
                        self.save('FederatesExporter updated model.', function (err) {
                            if (err) {
                                callback(err, self.result);
                                return;
                            }
                            self.result.setSuccess(true);
                            callback(null, self.result);
                        });
                    });
                })

            }else{
                self.result.setSuccess(true);
                callback(null, self.result);
            }
            
        }

        self.visitAllChildrenFromRootContainer(self.rootNode, function(err){
            if(err)
                self.logger.error(err);
            else
                finishExport(err);
        });

    };

    FederatesExporter.prototype.getChildSorterFunc = function(nodeType, self){
        var self = this,
            visitorName = 'generalChildSorter';

        var generalChildSorter = function(a, b) {

            //a is less than b by some ordering criterion : return -1;
            //if(self.isMetaTypeOf(a, self.META['Types'])){
            //    return -1;
            //}
            //a is greater than b by the ordering criterion: return 1;
            //if(self.isMetaTypeOf(b, self.META['Types'])){
            //    return 1;
            //}

            // a equal to b:
            return 0;
        };
        return generalChildSorter;
        
    }

    FederatesExporter.prototype.excludeFromVisit = function(node){
        var self = this,
            exclude = false;

        if(self.rootNode != node){    
            var nodeTypeName = self.core.getAttribute(self.getMetaType(node),'name');
            exclude = exclude 
            || self.isMetaTypeOf(node, self.META['Language [CASIM]'])
            || (self.federateTypes.hasOwnProperty(nodeTypeName) && !self.federateTypes[nodeTypeName].includeInExport);
        }
        if(exclude){
            self.logger.debug("node " + self.core.getAttribute(node, 'name') + "(" + self.core.getPath(node) + ") is excluded from the visit" );
        }
        
        return exclude;
    }

    FederatesExporter.prototype.getVisitorFuncName = function(nodeType){
        var self = this,
            visitorName = 'generalVisitor';
        if(nodeType){
            visitorName = 'visit_'+ nodeType;
            if(nodeType.endsWith('Federate')){
                visitorName = 'visit_'+ 'Federate';
            }
            
        }
        self.logger.debug('Genarated visitor Name: ' + visitorName);
        return visitorName;   
    }

    FederatesExporter.prototype.getPostVisitorFuncName = function(nodeType){
        var self = this,
            visitorName = 'generalPostVisitor';
        if(nodeType){
            visitorName = 'post_visit_'+ nodeType;
            if(nodeType.endsWith('Federate')){
                visitorName = 'post_visit_'+ 'Federate';
            }
        }
        self.logger.debug('Genarated post-visitor Name: ' + visitorName);
        return visitorName;
        
    }

    /*
    *
    * TRAVERSAL CODE - BEGIN
    *
    */

    FederatesExporter.prototype.ROOT_visitor = function(node){
        var self = this;
        self.logger.info('Visiting the ROOT');

        var root = {
            "@id": 'model:' + '/root',
            "@type": "gme:root",
            "model:name": self.projectName,
            "gme:children": []
        };

        return {context:{parent: root}};
    }

    FederatesExporter.prototype.visit_FOMSheet = function(node, parent, context){
        var self = this;

        self.fom_sheets[self.core.getPath(node)] = node;
        context['parent'] = {};
        return {context:context};
    }
    
    FederatesExporter.prototype.visit_Interaction = function(node, parent, context){
        var self = this,
        nodeType = self.core.getAttribute( self.getMetaType( node ), 'name' ),
        nodeBase = self.core.getAttribute( self.core.getBase( node ), 'name' ),
        nodeName = self.core.getAttribute( node, 'name' ),
        interaction = {};

        self.logger.debug('Node ' + nodeName + " is based on " + nodeBase + " with meta " + nodeType);
        self.interactions[self.core.getPath(node)] = interaction;
        
        interaction['name'] = self.core.getAttribute(node, 'name');
        interaction['delivery'] = self.core.getAttribute(node, 'Delivery');
        interaction['order'] = self.core.getAttribute(node, 'Order');
        interaction['inputPlaceName'] = "";
        interaction['outputPlaceName'] = "";
        interaction['mapperPublished'] = false;
        interaction['parameters'] = [];


        if(context.hasOwnProperty('interactions')){
            context['interactions'].push(interaction)
        }

        context['parentInteraction'] = interaction;

        return {context:context};
    }


    FederatesExporter.prototype.visit_Parameter = function(node, parent, context){
        var self = this;
        self.logger.debug('Visiting Parameter');
        if(context.hasOwnProperty('parentInteraction')){
            context['parentInteraction']['parameters'].push({
                name: self.core.getAttribute(node,'name'),
                parameterType: self.core.getAttribute(node,'ParameterType'),
                hidden: self.core.getAttribute(node,'Hidden'),
                position: self.core.getOwnRegistry(node, 'position')
            });
        }
        
        return {context:context};
    }


    FederatesExporter.prototype.visit_Object = function(node, parent, context){
        var self = this,
        object = {};
        self.logger.debug('Visiting Object');

        object['name'] = self.core.getAttribute(node, 'name');
        object['delivery'] = self.core.getAttribute(node, 'Delivery');
        object['order'] = self.core.getAttribute(node, 'Order');
        object['attributes'] = [];

        self.objects[self.core.getPath(node)] = object;

        if(context.hasOwnProperty('objects')){
            context['objects'].push(object)
        }

        context['parentObject'] = object;

        return {context:context};
    }

    FederatesExporter.prototype.visit_Attribute = function(node, parent, context){
        var self = this;
        self.logger.debug('Visiting Attribute');
        if(context.hasOwnProperty('parentObject')){
            context['parentObject']['attributes'].push({
                name: self.core.getAttribute(node,'name'),
                parameterType: self.core.getAttribute(node,'ParameterType'),
                hidden: self.core.getAttribute(node,'Hidden'),
                position: self.core.getOwnRegistry(node, 'position')
            });
        }
        
        return {context:context};
    }

    /*
    *
    * TRAVERSAL CODE - END
    *
    */
    return FederatesExporter;
});