// DO NOT EDIT THIS FILE
// This file is automatically generated from the webgme-setup-tool.
'use strict';


var config = require('webgme/config/config.default'),
    validateConfig = require('webgme/config/validator');


// The paths can be loaded from the webgme-setup.json
config.plugin.basePaths.push('src/plugins');
config.plugin.basePaths.push('src/common');

// Plugins
config.plugin.allowServerExecution = true;
config.plugin.allowBrowserExecution = true;

// Visualizer descriptors

// Add requirejs paths
config.requirejsPaths['c2wtng-meta'] = './src/common';
config.requirejsPaths['C2Core'] = './src/plugins/C2Core';
config.requirejsPaths['C2Federates'] = './src/plugins/C2Federates';
config.requirejsPaths['FederatesExporter'] = './src/plugins/FederatesExporter';
config.requirejsPaths['DeploymentExporter'] = './src/plugins/DeploymentExporter';


config.mongo.uri = 'mongodb://127.0.0.1:27017/c2_ng_modeler'
validateConfig(config);
module.exports = config;
